//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Froky.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FORNECEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORNECEDOR()
        {
            this.PRODUTO = new HashSet<PRODUTO>();
        }
    
        public int ID_FORNECEDOR { get; set; }
        public string CNPJ { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Nome Fantasia" )]
        public string RAZAO_SOCIAL { get; set; }
        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Telefone Primario")]
        public string TELEFONE_PRIMÁRIO { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Telefone Secundário")]
        public string TELEFONE_SECUNDÁRIO { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "E-mail")]
        public string E_MAIL { get; set; }

        public string NOME_FANTASIA { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO> PRODUTO { get; set; }
    }
}
