//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Froky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_COMPRA
    {
        public int ID_ITEM_COMPRA { get; set; }
        public Nullable<int> FK_PRODUTO { get; set; }
        public Nullable<int> FK_PEDIDO { get; set; }
        public Nullable<int> QUANTIDADE { get; set; }
        public Nullable<float> VALOR_UNIT { get; set; }
        public Nullable<float> VALOR_TOTAL { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
