//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Froky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.ITEM_COMPRA = new HashSet<ITEM_COMPRA>();
        }
    
        public int ID_PEDIDO { get; set; }
        public Nullable<System.DateTime> DATA_DA_COMPRA { get; set; }
        public Nullable<float> VALOR_TOTAL { get; set; }
        public string STATUS_DO_PEDIDO { get; set; }
        public Nullable<int> FK_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_COMPRA> ITEM_COMPRA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
