//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Froky.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.ITEM_COMPRA = new HashSet<ITEM_COMPRA>();
        }
    
        public int ID_PRODUTO { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Este é um campo obrigatório")]
        public string NOME { get; set; }

        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "Este é um campo obrigatório")]
        public string DESCRICAO { get; set; }

        [Display(Name = "Quantidade")]
        [Required(ErrorMessage = "Este é um campo obrigatório")]
        public Nullable<int> QUANTIDADE { get; set; }

        [Display(Name = "Preço Unitário")]
        [Required(ErrorMessage = "Este é um campo obrigatório")]
        public decimal PRECO { get; set; }


        public string IMAGEM { get; set; }

        
        [Required(ErrorMessage = "Este é um campo obrigatório")]
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "Categoria")]
        //[Required(ErrorMessage = "Este é um campo obrigatório")]
        public Nullable<int> FK_CATEGORIA { get; set; }


        [Display(Name = "Fornecedor ")]
        //[Required(ErrorMessage = "Este é um campo obrigatório")]
        public Nullable<int> FK_FORNECEDOR { get; set; }

        [Display(Name = "Categoria")]
        public virtual CATEGORIA CATEGORIA { get; set; }

        [Display(Name = "Fornecedor ")]
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_COMPRA> ITEM_COMPRA { get; set; }
    }
}
