//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Froky.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int ID_USUARIO { get; set; }
        public string CPF { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Nome")]
        public string NOME { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Tipo De Usuário")]
        public string TIPO_DE_USUARIO { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Genero")]
        public string SEXO { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Telefone Celular")]
        public string TELEFONE { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "E-mail")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Insira Um Endereço De E-mail Válido")]
        public string E_MAIL { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Senha")]
        [DataType(DataType.Password)]
        public string SENHA { get; set; }

        [Required(ErrorMessage = "Este é um campo obrigatório")]
        [Display(Name = "Data De Nascimento")]
        public Nullable<System.DateTime> DATA_DE_NASCIMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
